// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Transportadora.Data.Context;

#nullable disable

namespace Transportadora.Data.Migrations
{
    [DbContext(typeof(TransportadoraDbContext))]
    [Migration("20260611185833_SeedUser")]
    partial class SeedUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Transportadora.Models.Entities.Carga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("Altura");

                    b.Property<decimal>("Comprimento")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("Comprimento");

                    b.Property<string>("DescricaoNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Descricao_Nome");

                    b.Property<decimal>("Largura")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("Largura");

                    b.Property<decimal>("Peso")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("Peso");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.ToTable("Carga", (string)null);
                });

            modelBuilder.Entity("Transportadora.Models.Entities.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CEP");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Complemento");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Logradouro");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Numero");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("UF");

                    b.HasKey("Id");

                    b.ToTable("Endereco", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bairro = "Centro",
                            Cep = "00000001",
                            Cidade = "São Paulo",
                            Logradouro = "Rua Admin",
                            Numero = "1",
                            Uf = "SP"
                        },
                        new
                        {
                            Id = 2,
                            Bairro = "Centro",
                            Cep = "00000002",
                            Cidade = "São Paulo",
                            Logradouro = "Rua Atendente",
                            Numero = "2",
                            Uf = "SP"
                        },
                        new
                        {
                            Id = 3,
                            Bairro = "Centro",
                            Cep = "00000003",
                            Cidade = "São Paulo",
                            Logradouro = "Rua Cliente",
                            Numero = "3",
                            Uf = "SP"
                        });
                });

            modelBuilder.Entity("Transportadora.Models.Entities.Motorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Documento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Motorista", (string)null);
                });

            modelBuilder.Entity("Transportadora.Models.Entities.Ocorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Data_Hora");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.Property<int>("SolicitacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("Solicitacao_ID");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Tipo");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("User_ID");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoId");

                    b.HasIndex("UserId");

                    b.ToTable("Ocorrencia", (string)null);
                });

            modelBuilder.Entity("Transportadora.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Cliente"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Atendente"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Admin"
                        });
                });

            modelBuilder.Entity("Transportadora.Models.Entities.SolicitacaoColeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CargaId")
                        .HasColumnType("integer")
                        .HasColumnName("Carga_ID");

                    b.Property<int>("CriadoPorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("Criado_Por_User_ID");

                    b.Property<DateTime>("DataPrevistaRetirada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Data_Prevista_Retirada");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Data_Solicitacao");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("integer")
                        .HasColumnName("Destinatario_ID");

                    b.Property<int?>("MotoristaId")
                        .HasColumnType("integer")
                        .HasColumnName("Motorista_ID");

                    b.Property<string>("ObservacoesGerais")
                        .HasColumnType("text")
                        .HasColumnName("Observacoes_Gerais");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Prioridade");

                    b.Property<int>("RemetenteId")
                        .HasColumnType("integer")
                        .HasColumnName("Remetente_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<int?>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("Veiculo_ID");

                    b.HasKey("Id");

                    b.HasIndex("CargaId")
                        .IsUnique();

                    b.HasIndex("CriadoPorUserId");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("RemetenteId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Solicitacao_Coleta", (string)null);
                });

            modelBuilder.Entity("Transportadora.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Documento");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Email");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("integer")
                        .HasColumnName("Endereco_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Nome");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("Role_ID");

                    b.Property<string>("SenhaHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("SenhaHash");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Situacao");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EnderecoId");

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Documento = "00000000000",
                            Email = "admin@admin.com",
                            EnderecoId = 1,
                            Nome = "Administrador Master",
                            RoleId = 3,
                            SenhaHash = "9B968201AC99BBE67CEC3DF02251FAA383BE2B040732D00B0EF07C1600D97963",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 2,
                            Documento = "11111111111",
                            Email = "atendente@atendente.com",
                            EnderecoId = 2,
                            Nome = "Atendente Padrão",
                            RoleId = 2,
                            SenhaHash = "9B968201AC99BBE67CEC3DF02251FAA383BE2B040732D00B0EF07C1600D97963",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 3,
                            Documento = "22222222222",
                            Email = "cliente@cliente.com",
                            EnderecoId = 3,
                            Nome = "Cliente Fictício",
                            RoleId = 1,
                            SenhaHash = "9B968201AC99BBE67CEC3DF02251FAA383BE2B040732D00B0EF07C1600D97963",
                            Situacao = "Ativo"
                        });
                });

            modelBuilder.Entity("Transportadora.Models.Entities.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("Modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("Placa");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Veiculo", (string)null);
                });

            modelBuilder.Entity("Transportadora.Models.Entities.Ocorrencia", b =>
                {
                    b.HasOne("Transportadora.Models.Entities.SolicitacaoColeta", "Solicitacao")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Transportadora.Models.Entities.User", "User")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitacao");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Transportadora.Models.Entities.SolicitacaoColeta", b =>
                {
                    b.HasOne("Transportadora.Models.Entities.Carga", "Carga")
                        .WithOne("SolicitacaoColeta")
                        .HasForeignKey("Transportadora.Models.Entities.SolicitacaoColeta", "CargaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Transportadora.Models.Entities.User", "CriadoPorUser")
                        .WithMany("SolicitacoesCriadas")
                        .HasForeignKey("CriadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Transportadora.Models.Entities.User", "Destinatario")
                        .WithMany("SolicitacoesComoDestinatario")
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Transportadora.Models.Entities.Motorista", "Motorista")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transportadora.Models.Entities.User", "Remetente")
                        .WithMany("SolicitacoesComoRemetente")
                        .HasForeignKey("RemetenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Transportadora.Models.Entities.Veiculo", "Veiculo")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Carga");

                    b.Navigation("CriadoPorUser");

                    b.Navigation("Destinatario");

                    b.Navigation("Motorista");

                    b.Navigation("Remetente");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Transportadora.Models.Entities.User", b =>
                {
                    b.HasOne("Transportadora.Models.Entities.Endereco", "Endereco")
                        .WithMany("Users")
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Transportadora.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Transportadora.Models.Entities.Carga", b =>
                {
                    b.Navigation("SolicitacaoColeta");
                });

            modelBuilder.Entity("Transportadora.Models.Entities.Endereco", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Transportadora.Models.Entities.Motorista", b =>
                {
                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("Transportadora.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Transportadora.Models.Entities.SolicitacaoColeta", b =>
                {
                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("Transportadora.Models.Entities.User", b =>
                {
                    b.Navigation("Ocorrencias");

                    b.Navigation("SolicitacoesComoDestinatario");

                    b.Navigation("SolicitacoesComoRemetente");

                    b.Navigation("SolicitacoesCriadas");
                });

            modelBuilder.Entity("Transportadora.Models.Entities.Veiculo", b =>
                {
                    b.Navigation("Solicitacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
